#!/usr/bin/env python

"""The media bundles for audio enclave."""

def get_bundles(_MENCLAVE_ROOT):
    return (
        {"type": "javascript",
         "name": "aenclave-scripts",
         "path": _MENCLAVE_ROOT + "aenclave/scripts/",
         "url": "/audio/scripts/",
         "minify": True,
         "files": (
             "jquery-1.3.2.js",
             "jquery.clickmenu.js",
             "jquery.columnmanager.js",
             "jquery.cookie.min.js",
             "jquery.hotkeys.js",
             "jquery.tablednd_0_5.js",
             "controls.js",
             "channels.js",
             "fancyupload.js",
             "fileprogress.js",
             "filter.js",
             "playlist.js",
             "songlist.js",
             "swfupload.js",
             "swfupload.cookies.js",
             "swfupload.queue.js",
             "tablesort.js",
             "upload.js",
         )},

        {"type": "css",
         "name": "aenclave-styles",
         "path": _MENCLAVE_ROOT + "aenclave/styles/",
         "url": "/audio/styles/",
         "minify": True,
         "files": (
             "base.css",
             "browse.css",
             "clickmenu.css",
             "filter.css",
             "login.css",
             "playlist.css",
             "sftp_info.css",
             "songlist.css",
             "upload.css",
             # This is the sprites CSS file.
             "aenclave-sprites.css",
         )},

        {"type": "png-sprite",
         "name": "aenclave-sprites",
         "path": _MENCLAVE_ROOT + "aenclave/images/",
         "url": "/audio/images/",
         "css_file": _MENCLAVE_ROOT + "aenclave/styles/aenclave-sprites.css",
         "files": (
             "add.png",
             "cancel.png",
             "create.png",
             "cross.png",
             "delete.png",
             "dl.png",
             "edit.png",
             "email.png",
             "heart-gray.png",
             "heart-pink.png",
             "heart.png",
             "history.png",
             "maximize.png",
             "minimize.png",
             "new.png",
             "ok.png",
             "pause.png",
             "play.png",
             "remove.png",
             "selectcol.png",
             "shuffle.png",
             "skip.png",
             "sorta.png",
             "sortd.png",
             "speaker.png",
             "stop.png",
             "tick.png",
             "triangleselect.png",
             "updown.png",
         )},
    )
